version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  apt_packages:
    - libcurl4-openssl-dev
    - libssl-dev

sphinx:
   configuration: docs/conf.py

python:
   install:
   - requirements: app/requirements.txt
   - requirements: app/requirements.large.txt
