name: ce-docs

networks:
  internal:
    external: false

services:

  nginx:
    profiles:
      - "docs"
    image: nginx:1.26
    ports:
      - 127.0.0.1:4001:80
    networks:
      - internal
    volumes:
      - ../docs/build:/usr/share/nginx/html:ro

  sphinx:
    profiles:
      - "docs"
    image: blast-docs
    build:
      context: ..
      dockerfile: docs/Dockerfile
    networks:
      - internal
    command:
      - bash
      - -c
      - sphinx-build -a /opt/docs /opt/docs/build/
    volumes:
      - ../docs:/opt/docs
      - ../app:/app
